version: '3.8'

services:
  app:
    image: robgarciab/csv-service:latest
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads
    environment:
      - PORT=3000
      - RESET_TIME_MS=300000